### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by tryingsomestuff** [provostm/face-morphing-multiple-images#1]
Hi,

got this when try to use

```Traceback (most recent call last):
  File "/ssd/face-morphing-multiple-images/code/__init__.py", line 45, in <module>
    doMorphing(img1, img2, args.duration, args.frame, args.tmpfolder + str(i)+"_"+args.output)
  File "/ssd/face-morphing-multiple-images/code/__init__.py", line 13, in doMorphing
    [size, img1, img2, points1, points2, list3] = generate_face_correspondences(img1, img2)
  File "/ssd/face-morphing-multiple-images/code/face_landmark_detection.py", line 84, in generate_face_correspondences
    predictor = dlib.shape_predictor('code/utils/shape_predictor_68_face_landmarks.dat')
RuntimeError: Unable to open code/utils/shape_predictor_68_face_landmarks.dat
```

Any help will be appreciated.

Thanks a lot

**Comment by tryingsomestuff** [comment]
Oh I need the shape_predictor_68_face_landmarks.dat from the initial repo
